services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: docker/server/Dockerfile 
    restart: always
    ports:
      - "4000:4000"
  map:
    container_name: map
    build: 
      context: .
      dockerfile: docker/map/Dockerfile 
    restart: always
    ports:
      - "8090:8090"
    environment:
      - ID_PRESETS_CDN_URL=https://maps.megafete.ru/
    depends_on:
      - server